### ISSUE TITLE
User is immediately logged out after logging back in to same browser window

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#117]
### Bug Description

If logging out then logging back in, test server immediately logs user out after logging in. It is necessary to close the browser and start a new window to log back in.
### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bnygren** [comment]
Bug persists in TEST 1.0.11

**Comment by xlg8** [comment]
The problem is with the URL redirect @Iyanuu @bnygren . The log_out extension of the url does not change back to login after user logs in and logs out immediately https://test.afghanistan-apmis.com/sormas-ui/login#!dashboard_logout. Once you remove the added #!dashboard_logout, (https://test.afghanistan-apmis.com/sormas-ui/login) then log back in, it works. Please fix automatic redirect URL and this will be fixed. Thanks

**Comment by bnygren** [comment]
tested ok
