### ISSUE TITLE
Exclude archived data from the "all campaigns" drop down selection in Campaign Data

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#162]
### Problem Description

When a campaign is archived, still the data related to that campaign are displayed in the campaign data section when Campaign will be selected to "All Campaigns".

### Proposed Change

Do not show archived campaigns' data when "All Campaigns" is selected. Only show all active campaigns.

### Additional Information

![archived camp](https://user-images.githubusercontent.com/88741672/169744807-349dd2a7-1a94-46c4-8cd5-f32aa89a4135.png)

**Comment by bnygren** [comment]
@xlg8 Is this expected behavior or a bug actually?

**Comment by xlg8** [comment]
@bnygren Its the expected behaviour because archived campaign is a type of campaigns (active, archived) under all campaigns. So when you ask to see all campaigns, it would show all active and archived campaigns. What we would want to request to revise is to only allow active campaigns when all campaigns are requested and not show archived campaigns.
