### ISSUE TITLE
Day duplicate entry and auto calculation in Admin data

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#193]
### Feature Description

Tab validation:

- [x] Don't allow entry of duplicate days data per cluster per campaign

- [x] Auto calculation facility Day 1,2,3 to Day 4. (Admin data from)

Related to issues #66 and #70

**Comment by RaziaMahmodi** [comment]
> hi @RaziaMahmodi to confirm, are you testing on the live server or the test server?
> 
> For context, our approach has been to ensure duplicate data cannot be submitted. On clicking the "new form" button and the form is selected, users are prompted to fill in the infrastructure data up to cluster, if no form exists for the cluster of the same form type, on the given day, a new form is presented to fill. If not, the user is redirected to the already saved form with the previous data for editing.

Hi. on test server.
![image](https://user-images.githubusercontent.com/88741672/179531434-2770503a-0534-4e9b-9763-6f694419fa51.png)

**Comment by Iyanuu** [comment]
Thank you. I will confirm from the devOps team if the feature has been pushed to the test server but I've noticed it is on the live server.

A form is filled 
![1](https://user-images.githubusercontent.com/39916066/179533023-d0917040-05ae-4285-95b7-59482a3c7250.jpg)

Prompt for infrastructure determines what action the user is allowed next
![2](https://user-images.githubusercontent.com/39916066/179533032-23d91c39-7197-4c84-b29b-d239d4320b31.jpg)

The user is redirected because the form name/type and infrastructure match data already submitted on the day.
![3](https://user-images.githubusercontent.com/39916066/179533036-6e04f5ba-6bc5-4f95-876a-9fedb9cb95ae.jpg)


![4](https://user-images.githubusercontent.com/39916066/179533039-d9254380-5de9-436c-9437-36f16ca4a5e6.jpg)

**Comment by RaziaMahmodi** [comment]
> Thank you. I will confirm from the devOps team if the feature has been pushed to the test server but I've noticed it is on the live server.
> 
> A form is filled ![1](https://user-images.githubusercontent.com/39916066/179533023-d0917040-05ae-4285-95b7-59482a3c7250.jpg)
> 
> Prompt for infrastructure determines what action the user is allowed next ![2](https://user-images.githubusercontent.com/39916066/179533032-23d91c39-7197-4c84-b29b-d239d4320b31.jpg)
> 
> The user is redirected because the form name/type and infrastructure match data already submitted on the day. ![3](https://user-images.githubusercontent.com/39916066/179533036-6e04f5ba-6bc5-4f95-876a-9fedb9cb95ae.jpg)
> 
> ![4](https://user-images.githubusercontent.com/39916066/179533039-d9254380-5de9-436c-9437-36f16ca4a5e6.jpg)

Thanks. I will test it again.

**Comment by RaziaMahmodi** [comment]
Done, thanks.

**Comment by ToluOlayinka** [comment]
FIXED: Duplicate which happens when you get the unsaved changes pop up.
