### ISSUE TITLE
Provide for server-side integration of R Shiny support for advanced visualizations 

### ISSUE THREAD

**Issue by apmis-org** [xlg8/APMIS-Project#419]
- [x] Set up R shiny server on staging server for migration plan 
- [x] Set up IDE to allow installation of R packages, components, and required plugins for running R scripts and testing on the R shiny server
- [x] #507 
- [x] #506 
- [x] Test shiny app integration

**Comment by bnygren** [comment]
Re: 2- Which packages will need to be specified. But @sundayAdu @DevSeg is it possible, with training, for us to install packages on the server instead to save the need for Cinoteck to have to do it each time? The need to install packages periodically will be ongoing. Generally, if we can access a code prompt for R this would be trivial. 
3- Let's discuss - There was a request to change the main URL so this would be dependent. I would also like input on the sub url. I'm not sure 'stats' is the best given that there may be more charts and figures than actual stats. Also having 'apmis' in the sub url on top of the url is unnecessary. 
5- I'm not quite sure how this will work and also, I think this would create risk. Updated packages can deprecate syntax (and be built for specific versions of R) and then scripts can need troubleshooting. Intentional manual package updating is probably preferable at least initially. 
6- This should be explained in detail or removed/made into its own issue
Thanks

**Comment by apmis-org** [comment]
@bnygren So we can install R packages by ourselves once Cinoteck sets up the root access terminal environment for us to run our Rscripts and packages within the server itself. Cinoteck has set up the R environment with its dedicated IP and port number, however, like we do with installing R and also installing the IDE Rstudio, we will need Cinoteck to set up the R IDE environment on the server in a terminal view to enable us run all our Rscripts and packages there. Also, the updating of packages and troubleshooting could be done by CDC on the IDE installed manually on the Ubuntu server for us to run all our scripts and packages on the server. Should not be a problem.

For the sub-domain, yes we can decide on what sub-domain URL to use. And wisely so, we do not want apmis in the sub-domain name as you said it might soon change. 

For 6, I will extend the explanation. It is just a test that would need to be done once we integrate the R shiny to the existing APMIS system

**Comment by apmis-org** [comment]
comment removed as NA

**Comment by bnygren** [comment]
> @bnygren So we can install R packages by ourselves once Cinoteck sets up the root access terminal environment for us to run our Rscripts and packages within the server itself. Cinoteck has set up the R environment with its dedicated IP and port number, however, like we do with installing R and also installing the IDE Rstudio, we will need Cinoteck to set up the R IDE environment on the server in a terminal view to enable us run all our Rscripts and packages there. Also, the updating of packages and troubleshooting could be done by CDC on the IDE installed manually on the Ubuntu server for us to run all our scripts and packages on the server. Should not be a problem.
> 
> For the sub-domain, yes we can decide on what sub-domain URL to use. And wisely so, we do not want apmis in the sub-domain name as you said it might soon change.
> 
> For 6, I will extend the explanation. It is just a test that would need to be done once we integrate the R shiny to the existing APMIS system

So, it sounds like we can remove checkbox for installing packages since it is something we do ourselves as explained above. i.e., Cinoteck just has to do anything preceding that for us to have access to the R console on ubuntu ("root access terminal environment ").

**Comment by apmis-org** [comment]
Yes sir

**Comment by apmis-org** [comment]
https://www.jquery-az.com/boots/demo.php?ex=12.0_1

**Comment by bnygren** [comment]
@danieltomabba @ToluOlayinka This issue description here was vague and some of the items did not seem actionable. Lot of prep work has been done already. I updated the list an added two specific pieces that are now standalone issues. Please add anything specific back that you feel should be in the checkbox list. Thanks

**Comment by RaziaMahmodi** [comment]
@danieltomabba Let's update this issue to reflect the current situation.

**Comment by bnygren** [comment]
@danieltomabba Are there any specific tasks remaining for this (like in box 2)? Can it be closed?

**Comment by danieltomabba** [comment]
All tasks have been completed now. I will close this issue
