### ISSUE TITLE
Adding Admin Cov Report as a tab on Report page

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#447]
A completeness report should be provided for each data form:

Administrative Coverage Report (DC Daily Compilation Sheet Day 1-4 H2H) for pending or missed data part (formid = REV_AdminCovDataH2H_Day1_4): Those clusters that there is no data in one day, more than one day, or all days.

related to issue #185

<html>
<body>

Region | province | district | Cluster Number | ccode | Admin_day1 | Admin_day2 | Admin_day3 | Admin_day4 | Message
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
East | Kunar | Shegal | 8 | 1306008 | 1 | 1 | 1 | 0 | Incomplete
East | Laghman | Alingar | 18 | 704018 | 1 | 1 | 0 | 1 | Incomplete
East | Laghman | Mehtarlam | 18 | 701018 | 0 | 0 | 0 | 0 | Incomplete
East | Laghman | Mehtarlam | 7 | 701007 | 1 | 1 | 0 | 1 | Incomplete
East | Nangarhar | Jalalabad | 25 | 601025 | 1 | 0 | 1 | 1 | Incomplete
East | Nangarhar | Surkhrod | 31 | 603031 | 0 | 0 | 0 | 0 | Incomplete

</body>
</html>

**Comment by abahsuccess** [comment]
Hi @RaziaMahmodi.  A solution to this issue is that each day will have an identifier embedded in the JSON form. The identifier MUST be 'admin day 1_4'. For each day's form, the admin needs to identify the specific field of that day to be completed. After identification, add a calculative field to check if the field has been identified; it should return 1. The field must have the following characteristics:
1. It should be calculatable and an expression field.
2. The field must be hidden using 'dependingOn' logic.
3. The field should end with '_readonly'. e.g admin_day_1_readonly, admin_day_2_readonly
