### ISSUE TITLE
Fix core admin unit hierarchy to match Afghanistan

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#482]
Throughout APMIS we still see incorrect hierarchy names in the database itself (not the labels). For example, this can cause the exported data to have the wrong header names. The error report for a ccode not found in import references "community". 

1. **Cluster** is the correct name but it is called "community". 
2. **Region** is the correct name but it is called "area".

**Comment by sundayAdu** [comment]
#202

**Comment by bnygren** [comment]
@sundayAdu Is this contained within #202 ?

**Comment by ToluOlayinka** [comment]
This issue would be Fixed once we fully push the new upgrade #202 @bnygren 
Thank you.

**Comment by bnygren** [comment]
great. thanks.

**Comment by RaziaMahmodi** [comment]
As per Sunday, this issue is possible to be done and takes more time. CDC team will provide the list of incorrect hierarchy names in the database to be corrected.

**Comment by bnygren** [comment]
@RaziaMahmodi What info is still needed for this issue description?

**Comment by bnygren** [comment]
Import template: 


![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/60660864/22f37aa5-22bf-4e2e-9497-ce94f9ebd2c8)

And:
External ID.

**Comment by RaziaMahmodi** [comment]
It is still shown the incorrect name in data type row.

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/65c53285-b1c9-496a-9b4a-c483477a971e)

**Comment by bnygren** [comment]
@RaziaMahmodi These are really the csv labels rather than the field names in the db but agreed they should be corrected as well. Thanks for noting this

**Comment by RaziaMahmodi** [comment]
@bnygren Do you think I can close this issue and create a new issue to address the csv labels?

**Comment by bnygren** [comment]
@RaziaMahmodi sounds good to create a new issue for the labels

**Comment by RaziaMahmodi** [comment]
@Eutit5 this issue is appearing again as described below:
 In exports of data Region has the variable name "area" and Province is called "region":

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">



Campaigns | Form | Region | RCode | Province | PCode | District | DCode | Cluster | Cluster Number
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
campaign | form | area | rcode | region | pcode | district | dcode | Cluster | clusternumber
Aug CR 2024 | ICM Supervisor S2S | South | 8 | Kandahar | 33 | Kandahar | 3301 | Pero Kalacha | 4
