### ISSUE TITLE
Redesign user page layout

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#552]
- [x] 1. Removing the Address section.

![add](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/9c2a49a5-a54a-4a2c-8db6-934bd0b87191)

- [x] 2. Deleting "EAG" from Form Access forms:
- [x] 3. Grouping Form Access forms by Campaign Phase: (ARCHIVE will be listed individually) 

![user](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/2cf433b7-846b-45c6-9743-1f28b69cc269)

**Comment by sundayAdu** [comment]
As we are waiting for more information on this ticket... is this not already resolved in Common User Logic?

**Comment by bnygren** [comment]
@sundayAdu We will provide a mockup. @RaziaMahmodi and I felt this page's content could be streamlined but we want to provide a clear suggestion/idea before you get started. Thanks
-- update: @RaziaMahmod edited the original issue description, which should be clear now, so no need for mockup unless we hear otherwise.
