### ISSUE TITLE
Mobile app should not allow users to refuse version update and still enter data - discuss with dev team

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#560]
Background: Users were using old version of mobile app and submitting data with incorrect formatting. All user must perform and update prior to current campaign. 

Currently there are 2 steps: Download and Install. 
- at first step ("App update required") users will have one now choice: Download
- at "Ready to install" screen, users will only have the install button now.

**Comment by bnygren** [comment]
updated after discussion with dev team 16-Nov

**Comment by RaziaMahmodi** [comment]
I was logged in to Staging and after changing the mobile app URL in setting to Test, because of the new mobile version I couldn't log in. So I had to download and install the new version from Test server. Now I have 2 APMIS mobile app on my phone. I believe when there is another new version available I am able to review this issue. We can discuss on the 2 APMIS mobile apps. 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/59aaf436-aa7a-41ec-97f0-47537d47a4da)

**Comment by RaziaMahmodi** [comment]
When there is a mobile app new version is available, I am able to check and review this issue.

**Comment by RaziaMahmodi** [comment]
I have version 33 on my phone, the process of updating to version 34, instead of only one choice for each step, there are "Close APMIS" and "Install Later" which are not necessary. User should have "Download" and "Install". Also, it seems the app is not updated even after going through the update process.

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/3c081963-f6e5-48f4-b39d-6831d70f6f92)
![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/ba699b4c-e3e1-4b1a-ac4a-3e73d3538187)
