### ISSUE TITLE
User Activity Summary page update

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#687]
- [x] 1. Add Export button on all tabs of User Activity Summary page.
- [x] 2. Also need to be able to sort by headers. As of now we cannot even copy the list as text

![Image](https://github.com/user-attachments/assets/785a8747-bc6a-4b5b-bf19-b57219010f16)

**Comment by bnygren** [comment]
Exporting is there, but I don't see a change in the sorting as you cannot sort by Timestamp or Action, only Username as you can in Live

**Comment by DevSeg** [comment]
@bnygren Thanks for the feedback. As we discussed in the showcase for this issue we did not include a sorting for the Action Column since the actions in those columns are usually the same. Same with the timestamp column when the data has been filtered.

**Comment by bnygren** [comment]
@DevSeg Sorry I missed that in the showcase. I am fine with not having a date sort since we can just filter easily. I am not clear about what actions are captured in the user activity summary. What are the possibilities? Right not it seems like only logging in is captured. If it never changes, then the column is not needed, only a report title. Thanks
