### ISSUE TITLE
Wrap long columns header text into multiple lines 

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#94]
### Problem Description

For long columns header text, use mouseover hover text to show full col label (title) while hovering.

### Additional Information

![11](https://user-images.githubusercontent.com/88741672/151195369-e416f74b-545c-42d9-81ca-b732efe123a6.JPG)

**Comment by Iyanuu** [comment]
![WhatsApp Image 2022-02-28 at 1 33 21 PM](https://user-images.githubusercontent.com/39916066/155985202-7531c56a-29e3-4fbc-bf4f-356cdbe28df0.jpeg)

@bnygren @xlg8 @RaziaMahmodi Text wrapping isn't fully available on the UI framework being used when working with grid headers. The picture above shows how it presents.

An alternative is to text wrap with fixed initial width. Users are still able to expand the width of each column to view the text fully, this also allows for a neater design. 
![WhatsApp Image 2022-02-28 at 1 36 19 PM](https://user-images.githubusercontent.com/39916066/155985927-daf5e4a5-0da9-4326-b6b3-a944abd2a938.jpeg)

**Comment by xlg8** [comment]
@Iyanuu Thanks for your input. We would suggest to have a hover on each header to fully shows the text header while having the fixed initial width expandable by user. @bnygren @RaziaMahmodi

**Comment by bnygren** [comment]
@ToluOlayinka Per discussion 2-Mar agreed that mouseover hover to show full col label (title) while hovering would be preferred solution. @RaziaMahmodi please add any addl comment or missing input.

**Comment by Iyanuu** [comment]
<img width="1439" alt="Screenshot 2022-03-23 at 14 12 50" src="https://user-images.githubusercontent.com/39916066/159707706-b917087e-1fdc-4a9b-8d62-4113804c6de2.png">

@xlg8 @bnygren @RaziaMahmodi @ToluOlayinka While working on this issue, we think showing the description of the wrapped column while hovering the column fields instead of the column headers could be a better alternative. This will ensure users do not have to scroll to the top of the grid to view the description in cases where the contents of the grid are larger than the viewport of the device been used.

The image attached is what it would look like. @xlg8 @RaziaMahmodi what do you think about this?
